routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/blog/category/{slug?}', 'App\Http\Controllers\BlogController@category')->name('category');

Route::get('/blog/article/{slug?}', 'App\Http\Controllers\BlogController@article')->name('article');

Route::group(['prefix'=>'admin', 'namespace'=>'App\Http\Controllers\Admin', 'middleware'=>['auth']], function() {
    Route::get('/', 'DashboardController@dashboard')->name('admin');
    Route::resource('/category', 'CategoryController', ['as'=>'admin']);
    Route::resource('/article', 'ArticleController', ['as'=>'admin']);
    Route::group(['prefix'=>'user_management', 'namespace'=>'\App\Http\Controllers\Admin\UserManagement'], function() {
      Route::resource('/user', 'UserController', ['as' => 'admin.user_management']);
    });
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserManagement/UserController.php
<?php

namespace App\Http\Controllers\Admin\UserManagement;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;

class UserController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return Application|Factory|View|Response
   */
  public function index()
  {
    return view('admin.user_management.users.index', [
        'users' => User::paginate(10)
    ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Application|Factory|View|Response
   */
  public function create()
  {
    return view('admin.user_management.users.create', [
        'user' => []
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param Request $request
   * @return Application|RedirectResponse|Response|Redirector|string
   */
  public function store(Request $request)
  {
    $validator = $request->validate([
        'name' => ['required', 'string', 'max:255'],
        'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
        'password' => ['required', 'string', 'min:6', 'confirmed'],
    ]);

    User::create([
        'name' => $request['name'],
        'email' => $request['email'],
        'password' => bcrypt($request['password'])
    ]);

    return redirect()->route('admin.user_management.user.index');
  }

  /**
   * Display the specified resource.
   *
   * @param User $user
   * @return Response
   */
  public function show(User $user)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param User $user
   * @return Application|Factory|View|Response
   */
  public function edit(User $user)
  {
    return view('admin.user_management.users.edit', [
        'user' => $user
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param Request $request
   * @param User $user
   * @return RedirectResponse
   */
  public function update(Request $request, User $user)
  {
    $validator = $request->validate([
        'name' => ['required', 'string', 'max:255'],
        'email' => ['required', 'string', 'email', 'max:255', \Illuminate\Validation\Rule::unique('users')->ignore($user->id),],
        'password' => ['nullable', 'string', 'min:6', 'confirmed'],
    ]);

    $user->name = $request['name'];
    $user->email = $request['email'];
    $request['password'] == null ? : $user->password = bcrypt($request['password']);
    $user->save();

    return redirect()->route('admin.user_management.user.index');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param User $user
   * @return RedirectResponse
   */
  public function destroy(User $user)
  {
    $user->delete();

    return redirect()->route('admin.user_management.user.index');
  }
}

resources/views/admin/user_management/users/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Create user @endslot
      @slot('parent') Main @endslot
      @slot('active') Users @endslot
    @endcomponent

    <hr>

    <form action="{{ route('admin.user_management.user.store') }}" method="post">
      {{ csrf_field() }}

      @include('admin.user_management.users.partials.form')

    </form>
  </div>
@endsection

resources/views/admin/user_management/users/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Edit user @endslot
      @slot('parent') Main @endslot
      @slot('active') Users @endslot
    @endcomponent

    <hr>

    <form action="{{ route('admin.user_management.user.update', $user) }}" method="post">
      {{ method_field('PUT') }}
      {{ csrf_field() }}

      @include('admin.user_management.users.partials.form')

    </form>
  </div>
@endsection

resources/views/admin/user_management/users/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Users list @endslot
      @slot('parent') Main @endslot
      @slot('active') Users @endslot
    @endcomponent

    <hr>

    <a href="{{route('admin.user_management.user.create')}}" class="btn btn-primary float-right mb-3">
      <b>+</b> Create user
    </a>

    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th class="text-right">Action</th>
      </tr>
      </thead>
      <tbody>
      @forelse($users as $user)
        <tr>
          <th>{{ $user->name }}</th>
          <td>{{ $user->email }}</td>
          <td class="text-right">
            <form onsubmit="return confirm('Delete article?');" action="{{ route('admin.user_management.user.destroy', $user) }}"
                  method="post">
              {{ method_field('DELETE') }}
              {{ csrf_field() }}

              <a class="btn btn-default p-0" href="{{ route('admin.user_management.user.edit',$user) }}">🖋️</a>
              <button class="btn p-0" type="submit">🗑</button>
            </form>
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="3" class="text-center"><h4>No data available</h4></td>
        </tr>
      @endforelse
      </tbody>
    </table>

    <div class="paginate text-center">
      {{ $users->links() }}
    </div>
  </div>
@endsection