routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/blog/category/{slug?}', 'App\Http\Controllers\BlogController@category')->name('category');

Route::get('/blog/article/{slug?}', 'App\Http\Controllers\BlogController@article')->name('article');

Route::group(['prefix'=>'admin', 'namespace'=>'App\Http\Controllers\Admin', 'middleware'=>['auth']], function() {
    Route::get('/', 'DashboardController@dashboard')->name('admin');
    Route::resource('/category', 'CategoryController', ['as'=>'admin']);
    Route::resource('/article', 'ArticleController', ['as'=>'admin']);
    Route::group(['prefix'=>'user_management', 'namespace'=>'\App\Http\Controllers\Admin\UserManagement'], function() {
      Route::resource('/user', 'UserController', ['as' => 'admin.user_management']);
    });
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Article extends Model
{
  protected $fillable = ['title', 'slug', 'description_short', 'description', 'image', 'image_show', 'meta_title', 'meta_description',
      'meta_keyword', 'published', 'viewed', 'created_by', 'modified_by'];
  /**
   * @var mixed
   */
  private $title;

  public function setSlugAttribute($value)
  {
    $this->attributes['slug'] = Str::slug(mb_substr($this->title, 0, 40) . '-' . \Carbon\Carbon::now()->format('dmyHi'), '-');
  }

  public function categories()
  {
    return $this->morphToMany('App\Models\Category', 'categoryable');
  }

  public function scopeLastArticles($query, $count)
  {
    return $query->orderBy('created_at', 'desc')->take($count)->get();
  }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\Category;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ArticleController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return Application|Factory|View|Response
   */
  public function index()
  {
    return view('admin.articles.index', [
        'articles' => Article::orderBy('created_at', 'desc')->paginate(10)
    ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Application|Factory|View|Response
   */
  public function create()
  {
    return view('admin.articles.create', [
        'article' => [],
        'categories' => Category::with('children')->where('parent_id', 0)->get(),
        'delimiter' => ''
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param Request $request
   * @return RedirectResponse
   */
  public function store(Request $request): RedirectResponse
  {
    $article = Article::create($request->all());

    if ($request->input('categories')) :
      $article->categories()->attach($request->input('categories'));
    endif;

    return redirect()->route('admin.article.index');
  }

  /**
   * Display the specified resource.
   *
   * @param Article $article
   * @return Response
   */
  public function show(Article $article)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param Article $article
   * @return Application|Factory|View|Response
   */
  public function edit(Article $article)
  {
    return view('admin.articles.edit', [
        'article' => $article,
        'categories' => Category::with('children')->where('parent_id', 0)->get(),
        'delimiter' => ''
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param Request $request
   * @param Article $article
   * @return RedirectResponse
   */
  public function update(Request $request, Article $article)
  {
    $article->update($request->except('slug'));

    $article->categories()->detach();
    if ($request->input('categories')) :
      $article->categories()->attach($request->input('categories'));
    endif;

    return redirect()->route('admin.article.index');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param Article $article
   * @return RedirectResponse
   * @throws Exception
   */
  public function destroy(Article $article)
  {
    $article->categories()->detach();
    $article->delete();

    return redirect()->route('admin.article.index');
  }
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Create article @endslot
      @slot('parent') Main @endslot
      @slot('active') Articles @endslot
    @endcomponent

    <hr>

    <form action="{{ route('admin.article.store') }}" method="post">
      {{ csrf_field() }}

      @include('admin.articles.partials.form')

      <input type="hidden" name="created_by" value="{{\Illuminate\Support\Facades\Auth::id()}}">
    </form>
  </div>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Edit article @endslot
      @slot('parent') Main @endslot
      @slot('active') Articles @endslot
    @endcomponent

    <hr>

    <form action="{{ route('admin.article.update', $article) }}" method="post">
      <input type="hidden" name="_method" value="put">
      {{ csrf_field() }}

      @include('admin.articles.partials.form')

      <input type="hidden" name="modified_by" value="{{ \Illuminate\Support\Facades\Auth::id() }}">
    </form>
  </div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Articles list @endslot
      @slot('parent') Main @endslot
      @slot('active') Articles @endslot
    @endcomponent

    <hr>

    <a href="{{route('admin.article.create')}}" class="btn btn-primary float-right mb-3">
      <b>+</b> Create article
    </a>

    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Published</th>
        <th class="text-right">Action</th>
      </tr>
      </thead>
      <tbody>
      @forelse($articles as $article)
        <tr>
          <th>{{ $article->title }}</th>
          <td>{{ $article->published }}</td>
          <td class="text-right">
            <form onsubmit="return confirm('Delete article?');"
                  action="{{ route('admin.article.destroy', $article) }}"
                  method="post">
              <input type="hidden" name="_method" value="DELETE">
              {{ csrf_field() }}

              <a class="btn btn-default p-0" href="{{ route('admin.article.edit',$article) }}">🖋️</a>
              <button class="btn p-0" type="submit">🗑</button>
            </form>
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="3" class="text-center"><h4>No data available</h4></td>
        </tr>
      @endforelse
      </tbody>
    </table>

    <div class="paginate text-center">
      {{ $articles->links() }}
    </div>
  </div>
@endsection