routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/blog/category/{slug?}', 'App\Http\Controllers\BlogController@category')->name('category');

Route::get('/blog/article/{slug?}', 'App\Http\Controllers\BlogController@article')->name('article');

Route::group(['prefix'=>'admin', 'namespace'=>'App\Http\Controllers\Admin', 'middleware'=>['auth']], function() {
    Route::get('/', 'DashboardController@dashboard')->name('admin');
    Route::resource('/category', 'CategoryController', ['as'=>'admin']);
    Route::resource('/article', 'ArticleController', ['as'=>'admin']);
    Route::group(['prefix'=>'user_management', 'namespace'=>'\App\Http\Controllers\Admin\UserManagement'], function() {
      Route::resource('/user', 'UserController', ['as' => 'admin.user_management']);
    });
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
  protected $fillable = ['title', 'slug', 'parent_id', 'published', 'created_by', 'modified_by'];
  /**
   * @var mixed
   */
  private $title;

  public function setSlugAttribute($value)
  {
    $this->attributes['slug'] = Str::slug(mb_substr($this->title, 0, 40) . '-' .\Carbon\Carbon::now()->format('dmyHi'), '-');
  }

  public function children(): \Illuminate\Database\Eloquent\Relations\HasMany
  {
    return $this->hasMany(self::class, 'parent_id');
  }

  public function articles(): \Illuminate\Database\Eloquent\Relations\MorphToMany
  {
    return $this->morphedByMany('App\Models\Article', 'categoryable');
  }

  public function scopeLastCategories($query, $count)
  {
    return $query->orderBy('created_at', 'desc')->take($count)->get();
  }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

class CategoryController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return Application|Factory|View|Response
   */
  public function index()
  {
    return view('admin.categories.index', [
        'categories' => Category::paginate(8)
      ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Application|Factory|View|Response
   */
  public function create()
  {
    return view('admin.categories.create', [
        'category' => [],
        'categories' => Category::with('children')->where('parent_id', '0')->get(),
        'delimiter' => ''
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param Request $request
   * @return RedirectResponse
   */
  public function store(Request $request): RedirectResponse
  {
    Category::create($request->all());

    return redirect()->route('admin.category.index');
  }

  /**
   * Display the specified resource.
   *
   * @param Category $category
   * @return Response
   */
  public function show(Category $category): Response
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param Category $category
   * @return Application|Factory|View|Response
   */
  public function edit(Category $category)
  {
    return view('admin.categories.edit', [
        'category' => $category,
        'categories' => Category::with('children')->where('parent_id', '0')->get(),
        'delimiter' => ''
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param Request $request
   * @param Category $category
   * @return RedirectResponse
   */
  public function update(Request $request, Category $category): RedirectResponse
  {
    $category->update($request->except('slug'));

    return redirect()->route('admin.category.index');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param Category $category
   * @return RedirectResponse
   * @throws Exception
   */
  public function destroy(Category $category): RedirectResponse
  {
    $category->delete();

    return redirect()->route('admin.category.index');
  }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Create category @endslot
      @slot('parent') Main @endslot
      @slot('active') Categories @endslot
    @endcomponent

    <hr>

      <form action="{{ route('admin.category.store') }}" method="post">
        {{ csrf_field() }}

        @include('admin.categories.partials.form')
      </form>
  </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Edit category @endslot
      @slot('parent') Main @endslot
      @slot('active') Categories @endslot
    @endcomponent

    <hr>

    <form action="{{ route('admin.category.update', $category) }}" method="post">
      <input type="hidden" name="_method" value="put">
      {{ csrf_field() }}

      @include('admin.categories.partials.form')
    </form>
  </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title')Category list @endslot
      @slot('parent')Main @endslot
      @slot('active')Categories @endslot
    @endcomponent

    <hr>

    <a href="{{route('admin.category.create')}}" class="btn btn-primary float-right mb-3">
      <b>+</b> Create category
    </a>

    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Published</th>
        <th class="text-right">Action</th>
      </tr>
      </thead>
      <tbody>
      @forelse($categories as $category)
        <tr>
          <th>{{ $category->title }}</th>
          <td>{{ $category->published }}</td>
          <td class="text-right">
            <form onsubmit="return confirm('Delete category?');"
                  action="{{ route('admin.category.destroy', $category) }}"
                  method="post">
              <input type="hidden" name="_method" value="DELETE">
              {{ csrf_field() }}

              <a class="btn btn-default p-0" href="{{ route('admin.category.edit',$category) }}">🖋️</a>
              <button class="btn p-0" type="submit">🗑</button>
            </form>
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="3" class="text-center"><h4>No data available</h4></td>
        </tr>
      @endforelse
      </tbody>
    </table>

    <div class="paginate text-center">
      {{ $categories->links() }}
    </div>
  </div>
@endsection